apiVersion: v1
kind: Secret
metadata:
  name: customer-service-backend-secret
  namespace: customer-service
  labels:
    app: customer-service-backend
    tier: backend
  annotations:
    maintainer: "SOAT - Grupo 75"
    description: "Segredos para acesso ao banco de dados PostgreSQL via aplicação"
type: Opaque
stringData:
  DB_USER: ${SOAT_DB_USER}
  DB_PASS: "${SOAT_DB_PASS}"
